core/ALU.v
core/ALU_Decoder.v
core/Control_Unit.v
core/Main_Decoder.v
core/Mux_3_by_1.v
core/PC_Adder.v
core/PC_module.v
core/Register_File.v
core/Sign_Extend.v
core/csr_trap_unit.v
core/decode_stage.v
core/ex_mem_registers.v
core/execute_stage.v
core/fetch_stage.v
core/hazard_unit.v
core/id_ex_registers.v
core/if_id_registers.v
core/load_unit.v
core/mem_wb_registers.v
core/memory_stage.v
core/mux.v
core/RV32IMA.v
core/store_unit.v
core/sys_decoder.v
core/writeback_stage.v
debug/mmu_debug_buffer.v
mmu/mmu_region_decode.v
mmu/mmu_tlb.v
mmu/mmu_super_tlb.v
mmu/mmu_ptw.v
mmu/mmu_top.v
mmu/mmu_core_wrapper.v
mmu/mmu_ip_wrapper.v
debug/cache_debug_buffer.v
cache/l1_icache.v
cache/l1_dcache.v
cache/l2_cache.v
cache/core_l1_wrapper.v
cache/cache_maintenance_tracker.v
coherence/coherence_manager.v
mmu/cache_controller_mmu.v
interconnect/ahb/ahb_lite_l1_adapter.v
interconnect/ahb/ahb_lite_l1_slave_adapter.v
boot/boot_ctrl.v
soc/quad_core_soc.v
soc/quad_core_soc_ahb.v
soc/quad_core_axi_wrapper.v
soc/quad_core_axi_wrapper_ahb.v
soc/quad_core_axi_wrapper_bootable.v
soc/quad_core_axi_wrapper_ahb_bootable.v
legacy_2core/round_robin_arbiter_2core.v
legacy_2core/RV32_IP_Wrapper.v
legacy_2core/RV32IMA_DualCore_Wrapper.v
legacy_2core/RV32IMA_DualCore_BoardTop.v
