core/ALU.v
core/ALU_Decoder.v
core/Control_Unit.v
core/Main_Decoder.v
core/Mux_3_by_1.v
core/PC_Adder.v
core/PC_module.v
core/Register_File.v
core/Sign_Extend.v
core/csr_trap_unit.v
core/decode_stage.v
core/ex_mem_registers.v
core/execute_stage.v
core/fetch_stage.v
core/hazard_unit.v
core/id_ex_registers.v
core/if_id_registers.v
core/load_unit.v
core/mem_wb_registers.v
core/memory_stage.v
core/mux.v
core/RV32IMA.v
core/store_unit.v
core/sys_decoder.v
core/writeback_stage.v
debug/cache_debug_buffer.v
cache/l1_icache.v
cache/l1_dcache.v
cache/l2_cache.v
cache/core_l1_wrapper.v
coherence/coherence_manager.v
interconnect/ahb/ahb_lite_l1_adapter.v
interconnect/ahb/ahb_lite_l1_slave_adapter.v
boot/boot_ctrl.v
soc/quad_core_soc.v
soc/quad_core_soc_ahb.v
