`timescale 1ns / 1ps

// AXI boundary regression. The coherence manager intentionally emits a
// one-cycle mem_req_valid pulse; the wrapper must latch it and hold each
// AXI VALID plus payload through arbitrary READY backpressure.
module tb_axi_request_hold;
    reg clk = 1'b0;
    always #5 clk = ~clk;
    reg resetn;
    integer errors;

    wire [31:0] awaddr, wdata, araddr;
    wire awvalid, wvalid, bready, arvalid, rready;
    wire [3:0] wstrb;
    reg awready, wready, bvalid, arready, rvalid;
    reg [1:0] bresp, rresp;
    reg [31:0] rdata;

    quad_core_axi_wrapper dut (
        .ACLK(clk), .ARESETN(resetn), .Mmu_Flush(1'b0), .Cache_Flush(1'b0),
        .ResultW0(), .ResultW1(), .ResultW2(), .ResultW3(),
        .Fetch_PageFault0(), .Fetch_PageFault1(), .Fetch_PageFault2(), .Fetch_PageFault3(),
        .Data_PageFault0(), .Data_PageFault1(), .Data_PageFault2(), .Data_PageFault3(),
        .M_AXI_AWADDR(awaddr), .M_AXI_AWVALID(awvalid), .M_AXI_AWREADY(awready),
        .M_AXI_WDATA(wdata), .M_AXI_WSTRB(wstrb), .M_AXI_WVALID(wvalid), .M_AXI_WREADY(wready),
        .M_AXI_BRESP(bresp), .M_AXI_BVALID(bvalid), .M_AXI_BREADY(bready),
        .M_AXI_ARADDR(araddr), .M_AXI_ARVALID(arvalid), .M_AXI_ARREADY(arready),
        .M_AXI_RDATA(rdata), .M_AXI_RRESP(rresp), .M_AXI_RVALID(rvalid), .M_AXI_RREADY(rready)
    );

    task check;
        input condition;
        input [8*96-1:0] name;
        begin
            if (!condition) begin
                errors = errors + 1;
                $display("[FAIL] %0s", name);
            end
            else $display("[PASS] %0s", name);
        end
    endtask

    task pulse_internal_request;
        input we;
        input [31:0] addr;
        input [31:0] data;
        input [3:0] strb;
        begin
            force dut.mem_req_valid = 1'b1;
            force dut.mem_we        = we;
            force dut.mem_addr      = addr;
            force dut.mem_wdata     = data;
            force dut.mem_wstrb     = strb;
            @(posedge clk);
            #1;
            force dut.mem_req_valid = 1'b0;
            @(posedge clk);
            #1;
            release dut.mem_req_valid;
            release dut.mem_we;
            release dut.mem_addr;
            release dut.mem_wdata;
            release dut.mem_wstrb;
        end
    endtask

    initial begin
        errors = 0;
        resetn = 1'b0;
        awready = 0;
        wready = 0;
        bvalid = 0;
        bresp = 0;
        arready = 0;
        rvalid = 0;
        rresp = 0;
        rdata = 0;
        repeat (4) @(posedge clk);
        @(negedge clk);
        resetn = 1'b1;

        pulse_internal_request(1'b0, 32'h8000_1234, 32'b0, 4'b0);
        check(arvalid && araddr == 32'h8000_1234,
              "read request pulse is latched onto ARVALID and ARADDR");
        repeat (3) begin
            @(posedge clk); #1;
            check(arvalid && araddr == 32'h8000_1234,
                  "ARVALID/address remain stable while ARREADY is low");
        end
        @(negedge clk); arready = 1'b1;
        @(posedge clk); #1;
        @(negedge clk); arready = 1'b0;
        check(!arvalid && rready, "AR handshake retires address phase and enables read response");
        @(negedge clk); rdata = 32'hCAFE_BABE; rvalid = 1'b1;
        #1;
        check(rready && dut.mem_valid && !dut.mem_error,
              "RVALID/RREADY completion returns one clean mem_valid pulse");
        @(posedge clk); #1;
        @(negedge clk); rvalid = 1'b0;

        // Reset isolates the write check from fetch traffic generated by
        // the embedded cores after the forced request is released.
        resetn = 1'b0;
        repeat (3) @(posedge clk);
        @(negedge clk); resetn = 1'b1;
        pulse_internal_request(1'b1, 32'hC000_0040, 32'h0000_5A00, 4'b0010);
        check(awvalid && wvalid && awaddr == 32'hC000_0040 &&
              wdata == 32'h0000_5A00 && wstrb == 4'b0010,
              "write request latches address, data and uncached byte strobe");
        repeat (2) begin
            @(posedge clk); #1;
            check(awvalid && wvalid && wstrb == 4'b0010,
                  "AWVALID/WVALID payload remains stable under joint backpressure");
        end
        @(negedge clk); awready = 1'b1;
        @(posedge clk); #1;
        @(negedge clk); awready = 1'b0;
        check(!awvalid && wvalid, "independent AW handshake does not drop pending WVALID");
        repeat (2) @(posedge clk);
        @(negedge clk); wready = 1'b1;
        @(posedge clk); #1;
        @(negedge clk); wready = 1'b0;
        check(!wvalid && bready, "independent W handshake waits for write response");
        @(negedge clk); bresp = 2'b10; bvalid = 1'b1;
        #1;
        check(bready && dut.mem_valid && dut.mem_error,
              "BRESP error completes the latched request with mem_error");
        @(posedge clk); #1;
        @(negedge clk); bvalid = 1'b0;

        if (errors == 0) $display("AXI_REQUEST_HOLD_TB: PASS");
        else             $display("AXI_REQUEST_HOLD_TB: FAIL (%0d errors)", errors);
        $finish;
    end
endmodule
