# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/Study/KLTN/Risc_V_new/Risc_V/Risc_V.runs/synth_1/RV32IMFA_DualCore_BoardTop.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z030fbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Study/KLTN/Risc_V_new/Risc_V/Risc_V.cache/wt [current_project]
set_property parent.project_path D:/Study/KLTN/Risc_V_new/Risc_V/Risc_V.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Study/KLTN/Risc_V_new/Risc_V/Risc_V.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  D:/Study/KLTN/Risc_V_new/Risc_V/mem/memfileA.mem
  D:/Study/KLTN/Risc_V_new/Risc_V/mem/programM.mem
  D:/Study/KLTN/Risc_V_new/Risc_V/mem/program.mem
  D:/Study/KLTN/Risc_V_new/Risc_V/mem/programF.mem
}
read_verilog -library xil_defaultlib {
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/ALU.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/ALU_Decoder.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/Control_Unit.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/FP_sqrt.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/FP_CVT.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/FP_FMA.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/FP_Mul.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/FP_Add.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/FPU.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/FPU_Decoder.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/FP_Div.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/FP_Register_File.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/Main_Decoder.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/Mux_3_by_1.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/PC_Adder.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/PC_module.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/RV32IMFA.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/RV32IMFA_DualCore_Wrapper.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/Register_File.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/Sign_Extend.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/decode_stage.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/ex_mem_registers.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/execute_stage.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/fetch_stage.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/hazard_unit.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/id_ex_registers.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/if_id_registers.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/mem_wb_registers.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/memory_stage.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/mux.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/round_robin_arbiter_2core.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/writeback_stage.v
  D:/Study/KLTN/Risc_V_new/Risc_V/rtl/RV32IMFA_DualCore_BoardTop.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Study/KLTN/Risc_V_new/Risc_V/constraints/riscv.xdc
set_property used_in_implementation false [get_files D:/Study/KLTN/Risc_V_new/Risc_V/constraints/riscv.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top RV32IMFA_DualCore_BoardTop -part xc7z030fbv676-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RV32IMFA_DualCore_BoardTop.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RV32IMFA_DualCore_BoardTop_utilization_synth.rpt -pb RV32IMFA_DualCore_BoardTop_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
